### ISSUE TITLE
gitignore 관련 확인

### ISSUE THREAD

**Issue by LeeKyoungIl** [monkeyDugi/ballondor#1]
지금 github repository 보면 필요없는 파일들도 repo에 들어가 있습니다.

.setting, target 등등은 필요가 없죠 

gitignore 를 검색해서 적용해 보세요.

**Comment by monkeyDugi** [comment]
적용 완료했습니다.
그런데 의문이 있네요.

1. root-context.xml 같은 DB 정보가 있는 파일은 ignore 시켜야 맞는건 알겠는데
   다른 pom.xml, web.xml target폴더 등등 굳이 ignore시킬 필요가 있나요??

2. 하지만 다르게 드는 생각은 git이라는 건 원격 저장소로써 단순히 프로젝트 전체를 백업하기 위한 
   용도로 사용할 수도 있는데 그런 경우에는 굳이 ignore를 사용하지 않아도 되는 걸까요?

3. pom.xml 같은 경우는 협업개발 시 간혹 라이브러리 추가가 될 수도 있을 것 같은데 그런경우는
    pom.xml이 공유 되어야 하지 않나요?

4. git에 올리는건 기본적인 소스파일만 올라가야 하는건가요?
    정확하게 어떤 파일들을 ignore 시켜야 하는지 기준이 잡히지 않네요.
    제가 생각하는 ignore의 기준은 프로젝트 마다 기준이 다르듯 각 프로젝트에 필요 없다고 
    판단되는 파일을 정하는 것 같습니다. 즉, 매번 ingnore 시킬 파일은 달라질 것 같습니다.

**Comment by LeeKyoungIl** [comment]
디비정보가 있는 파일은 ignore 시키는게 아닙니다. 다만 이렇게 공개적인 repo 에서는 그게 맞지만 
회사내의 git에는 포함시키는게 맞습니다. 

그리고 gitignore 의 대상은 **컴파일로서 생성된 파일들을 대상**으로 합니다. 
또 tmp 나 log 같은 파일 도 포함 됩니다. 

따라서 target 만 시키면 되며 pom.xml 이나 web.xml 은 ignore 대상이 아닙니다.

**Comment by LeeKyoungIl** [comment]
pom.xml 이나 web.xml 등 추가해 주세요; 이러면 프로젝트 빌드 자체가 안됩니다;

https://github.com/LeeKyoungIl/illuminati/tree/master/illuminati

참고하세요.
