### ISSUE TITLE
lombok 적용해보기

### ISSUE THREAD

**Issue by LeeKyoungIl** [monkeyDugi/ballondor#2]
지금 프로젝트에 필요없는 boilerplate code 등이 많이 포함되어있습니다. (logger 포함)

lombok을 적용해서 boilerplate code 를 제거해 보세요.

**Comment by monkeyDugi** [comment]
.gitignore, lombok 적용완료 했습니다.

lombok 목록
- @Getter, @Setter, @ToString

**Comment by LeeKyoungIl** [comment]
잘하셨습니다.

![image](https://user-images.githubusercontent.com/4101636/64707160-94c84000-d4ed-11e9-831e-c2b764870875.png)

이런 클래스 보면 생성자를 코딩 안하셨는데요. 
사실 안쓰셔도 상관없습니다. 이 안써도 되는 이유가 뭘까요?

**Comment by monkeyDugi** [comment]
생각을 할수록 뭔가 더 어렵네요..
기본이 굉장히 부족하다는걸 느꼈습니다!

생성자를 사용하는 방법은 알겠는데 
사용하지 않아도 되는 이유는 뭔가 제대로 확실한 이유가 서지 않네요
보통 VO를 사용할 때 쿼리와 연관된 것을 쿼리의 컬럼과 이름을 맞추어 사용한다. 라고만 생각하고 사용을 했었습니다. 생성자에 대해서 따로 깊게 생각을 한 적이 없었던 것 같아요
내일까지 더 찾아보고 말씀드릴게요!!

**
대략 이런 내용을 테스트 해봤습니다. 옛날에 배웠던 내용이기억이 나네요 :)
![11](https://user-images.githubusercontent.com/53487385/64922569-8ccd1080-d80b-11e9-88ab-c966fbc047c8.PNG)

**Comment by monkeyDugi** [comment]
변수 초기화 방법에는 크게 두 가지가 있습니다.
1. 명시적 초기화 ( String work = "공부" )
2. 생성자 초기화 ( SearchDtlWorLIstDto dtl  = new SearchDtlWorLIstDto() )

명시적 초기화는 변수에 1번처럼 변수값만 초기화 시킬 때 사용되고,
생성자 초기화는 하나의 메서드로써 변수 초기화 이외에도 다른 기능을 넣을 때 사용하는 기능이라고 생각합니다. 
예를 들어 생성자에서 하는 일이 변수 초기화, 초기화 된 변수들의 연산, 연산된 데이터 출력 등
이런 기능들이 필요할 때 사용되는게 적절 하다고 생각합니다.

DB에서 가져오는 데이터 타입과 명이 SearchDtlWorLIstDto와 같기 때문에 변수 초기화도 되는 것 같습니다. 명시적 초기화의 개념으로요. 
즉, 명시적 초기화 개념을 DTO 변수에 몰아넣고, DB데이터를 받아 한 번에 명시적 초기화를 하고,
초기화 된 객체를 ajax로 리턴하는 방법을 사용하고 있는 것 입니다.

물론 생성자를 생성하지 않는다면 기본 생성자는 존재하고, 해당 코드는 기본 생성자를  사용하지 않는 코드라고 생각합니다.

**Comment by LeeKyoungIl** [comment]
산당히 단순한 질문인데 많은 생각을 하셨네요. 

기본 생성자를 코딩하지 않아도 문제가 없는 이유는...
기본 생성자는 다른 생성자를 정의하지 않으면 인수가없는 생성자가 자동으로 컴파일러가 생성해 줍니다. ^^

**Comment by monkeyDugi** [comment]
아.. 제가 너무 깊게 생각했네요.. ㅎㅎ
혹시 제가 설명한 것들 중 틀린 개념이 있나요??

**Comment by LeeKyoungIl** [comment]
생성자 초기화는 하나의 메서드로써 변수 초기화 이외에도 다른 기능을 넣을 때 사용하는 기능이라고 생각합니다.
라기 보단 생성자 초기화는 객체를 생성해 주는 초기화 개념이라고 생각하시면 됩니다.

**Comment by LeeKyoungIl** [comment]
https://github.com/monkeyDugi/ballondor/issues/13
요 이슈에 정리해 보아요.
